appversion: dev
env: beta
http_host: beta.zestedesavoir.com
certificate:
  cert: /etc/letsencrypt/live/beta.zestedesavoir.com/fullchain.pem
  key: /etc/letsencrypt/live/beta.zestedesavoir.com/privkey.pem
very_top_banner:
  background_color: '#800'
  border_color: '#450000'
  color: 'white'
  message: 'Version bÃªta'
