---
# For a PR: pull/xxxx/head
# For a branch or a tag: just its name
appversion: dev
env: beta
http_host: beta.zestedesavoir.com
backupdir: /opt/sauvegarde
enable_https: true
certificate:
  cert: /etc/letsencrypt/live/beta.zestedesavoir.com/fullchain.pem
  key: /etc/letsencrypt/live/beta.zestedesavoir.com/privkey.pem
munin_certificate:
  cert: /etc/letsencrypt/live/munin.beta.zestedesavoir.com/fullchain.pem
  key: /etc/letsencrypt/live/munin.beta.zestedesavoir.com/privkey.pem
very_top_banner:
  background_color: "#800"
  border_color: "#450000"
  color: white
  message: Version bÃªta
  slug: version-beta
