---
install_zds: false
env: matomo
http_host: matomo.zestedesavoir.com
mysql:
  user: matomo
  password: matomo
  name: matomo
enable_https: true
certificate:
  cert: /etc/letsencrypt/live/matomo.zestedesavoir.com/fullchain.pem
  key: /etc/letsencrypt/live/matomo.zestedesavoir.com/privkey.pem
matomo_webroot: /opt/matomo
matomo_version: 5.3.2
