---
repos:
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v24.12.2 # doit aussi être mis à jour dans requirements.txt
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
