---
dist: bionic

language: ruby
cache: bundler

# docker is required to run tests
services: docker

before_install:
  # install bundler 2.x
  - gem install bundler

install:
  - bundle install

script:
  # run kitchen tests (destroy, create, converge, setup, verify and destroy)
  - kitchen test
