---
workdir: /opt/zds
rundir: "{{ workdir }}/run"
appdir: "{{ workdir }}/app"
datadir: "{{ workdir }}/data"
webroot: "{{ workdir }}/webroot"
virtualenv: "{{ workdir }}/virtualenv"
logdir: /var/log/zds
appuser: zds
apprepo: "https://github.com/zestedesavoir/zds-site.git"
env: dev
secrets: []
