- include_role:
    name: common
    tasks_from: nodejs
  tags:
    - bootstrap

- name: installing frontend
  npm: path="{{ appdir }}"
  become: true
  become_user: "{{ appuser }}"

- name: building frontend
  command: npm run build
  args:
    chdir: "{{ appdir }}"
  become: true
  become_user: "{{ appuser }}"
