appversion: v30.1c-artemis
env: prod
public: true
http_host: zestedesavoir.com
certificate:
  cert: /etc/letsencrypt/live/www.zestedesavoir.com/fullchain.pem
  key: /etc/letsencrypt/live/www.zestedesavoir.com/privkey.pem
