---
appversion: v31.1
env: prod
public: true
http_host: zestedesavoir.com
enable_https: true
certificate:
  cert: /etc/letsencrypt/live/www.zestedesavoir.com/fullchain.pem
  key: /etc/letsencrypt/live/www.zestedesavoir.com/privkey.pem
munin_certificate:
  cert: /etc/letsencrypt/live/munin.zestedesavoir.com/fullchain.pem
  key: /etc/letsencrypt/live/munin.zestedesavoir.com/privkey.pem
pass_manager_host: "vault-ro.{{ http_host }}"
pass_manager_certificate:
  cert: "/etc/letsencrypt/live/{{ pass_manager_host }}/fullchain.pem"
  key: "/etc/letsencrypt/live/{{ pass_manager_host }}/privkey.pem"
